version: "2.38.1"
services: 
   node-app:
    build:
      context: .
      target: development
    volumes:
      - .:/app:ro
    # environment:
    #   - NODE_ENV=development
    # command: npm run dev 
   
    